[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0.66"

[dev-dependencies]
pretty_assertions = "1.4.1"
